# Copyright (c) 2026 3zwr1 (AMDNR). Part of AMDNR (GPL-3.0; see Licenses/AMDNR_NOTICE.txt).
# SPDX-License-Identifier: GPL-3.0-or-later
"""Build the AMDNR Screen GI compute shaders into precompiled headers (design 3.4).

usage: python build_gi_shaders.py [--verify] [--only NAME[,NAME...]]
  Compiles every gi_<pass>.hlsl of this folder with the Windows SDK DXC:
    -T cs_6_2 -E main -HV 2021 -enable-16bit-types -O3 -Qstrip_debug -Qstrip_reflect
    -Fh ..\\precompiled\\gi_<pass>.h -Vn g_gi_<pass>
  and puts the AMDNR copyright line on top of each generated header (DXC does not write one).
  --verify rebuilds into a temporary folder and compares with the checked-in headers (exit 1 on a difference).
Last line: "BUILD_GI_SHADERS PASS|FAIL ..."; exit 0 = PASS.
"""
from __future__ import annotations

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

# Set AMDNR_DXC to the Windows SDK dxc.exe, or put it on PATH; the last value is the usual SDK location.
DXC = os.environ.get("AMDNR_DXC") or shutil.which("dxc") or (
    r"C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\dxc.exe")
HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "precompiled")
PASSES = ["prepass", "pyramid", "trace", "temporal", "spatial", "composite", "debug"]
COPYRIGHT = "// Copyright (c) 2026 3zwr1 (AMDNR). Part of AMDNR (GPL-3.0; see Licenses/AMDNR_NOTICE.txt).\n"


def build(name: str, out_dir: str) -> str:
    src = os.path.join(HERE, "gi_" + name + ".hlsl")
    tmp = os.path.join(out_dir, "gi_" + name + ".dxc.h")
    dst = os.path.join(out_dir, "gi_" + name + ".h")
    args = [DXC, "-T", "cs_6_2", "-E", "main", "-HV", "2021", "-enable-16bit-types", "-O3", "-Qstrip_debug",
            "-Qstrip_reflect", "-I", HERE, src, "-Fh", tmp, "-Vn", "g_gi_" + name]
    res = subprocess.run(args, capture_output=True, text=True)
    if res.returncode != 0:
        sys.stdout.write(res.stdout)
        sys.stdout.write(res.stderr)
        raise SystemExit("BUILD_GI_SHADERS FAIL dxc failed for gi_" + name + ".hlsl")
    if res.stderr.strip():
        sys.stdout.write(res.stderr)
    with open(tmp, "r", encoding="utf-8", errors="replace") as f:
        body = "\n".join(line.rstrip() for line in f.read().replace("\r\n", "\n").splitlines())
    os.remove(tmp)
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write(COPYRIGHT)
        f.write("// Generated by dlssnr/gi/shaders/build_gi_shaders.py from gi_" + name + ".hlsl. Do not edit.\n")
        f.write(body)
        f.write("\n")
    return dst


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--only", default="")
    a = ap.parse_args()
    names = [n for n in a.only.split(",") if n] or PASSES
    for n in names:
        if n not in PASSES:
            print("BUILD_GI_SHADERS FAIL unknown pass " + n + " (known: " + ", ".join(PASSES) + ")")
            return 1
    if a.verify:
        diffs = []
        with tempfile.TemporaryDirectory() as t:
            for n in names:
                built = build(n, t)
                checked = os.path.join(OUT, "gi_" + n + ".h")
                with open(built, "rb") as fa:
                    new = fa.read()
                old = b""
                if os.path.exists(checked):
                    with open(checked, "rb") as fb:
                        old = fb.read()
                same = new == old
                print(n + ": " + ("same" if same else "DIFFERENT"))
                if not same:
                    diffs.append(n)
        print("BUILD_GI_SHADERS " + ("PASS" if not diffs else "FAIL") + " verify=" + str(len(names)) +
              " different=" + str(len(diffs)))
        return 0 if not diffs else 1
    os.makedirs(OUT, exist_ok=True)
    for n in names:
        dst = build(n, OUT)
        print(n + ": " + str(os.path.getsize(dst)) + " bytes -> precompiled/gi_" + n + ".h")
    print("BUILD_GI_SHADERS PASS built=" + str(len(names)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
